name: test echo

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: test multple echo
        run: |
          echo "MAVEN_USERNAME=${MAVEN_USERNAME}"
          echo "MAVEN_USER_PASSWORD=${MAVEN_USER_PASSWORD}"
          echo "MAVEN_GPG_PASSPHRASE=${MAVEN_GPG_PASSPHRASE}"
          echo "MAVEN_GPG_PRIVATE_KEY=${MAVEN_GPG_PRIVATE_KEY}"
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_USER_PASSWORD: ${{ secrets.MAVEN_USER_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
          MAVEN_GPG_PRIVATE_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
